---
name: Oscar Rivas Delgado
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: BCom(Hons), BSc
position: Business Engineering student 
address: Jr Campania 208 Bellavista, Callao
phone: +51 949767204
email: oj.rivasd@alum.up.edu.pe
github: MRCORD
linkedin: MRCORD
headcolor: 414141
output: vitae::awesomecv
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```

# Education
```{r}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "Bachelor of Business Engineering", "Universidad del Pacífico", "Lima, Perú", "Aug. 2016 - Present", "WAM of 14.4",
  "Bachelor of Business Engineering", "Universidad del Pacífico", "Lima, Perú", "Aug. 2016 - Present", "111 Credits recognized",
  "Bsc of Management & Digital Innovation", "University of London - London School of Economics", "Lima, Perú", "Oct. 2018 - Present", "Marks pending",

) %>% 
  detailed_entries(degree, dates, uni, loc, details)
```

# Experience
```{r}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Data science intern", "Credo consulting", "Lima, Perú", "Mar. 2019 - Present", "Data parsing"
) %>% 
  detailed_entries(role, dates, company, loc, details)
```

\newpage

<!-- # Relevant Skills -->
<!-- ```{r} -->
<!-- cvskill("Data Analysis", c("Visualisation", "Data Cleaning", "Forecasting", "Modelling", "Communication", "Inference", "Machine Learning", "Web Scraping")) -->
<!-- cvskill("Programming", c("R", "Python", "SQL", "Java", "C", "C++", "HTML/CSS", "TeX", "MATLAB")) -->
<!-- ``` -->

# Awards & Achievements
## Awards
```{r}
tribble(
  ~ award, ~ from, ~ year,
  "Commerce Dean's Honour", "Monash", "2017",
  "Commerce Dean's Commendation", "Monash", "2016",
  "Science Dean’s List", "Monash", "2014-2016",
  "International Institute of Forecasters Award", "IIF", "2014",
  "Rotary Youth Leadership Award", "Rotary", "2013"
) %>%
  brief_entries(award, year, from)
```


## Competitions
```{r}
tribble(
  ~ competition, ~ from, ~ year,
  "UseR! 2018 Datathon Champion", "UseR!", "2018",
  "RMIT SBITL Analytics Competition Champion", "RMIT", "2017",
  "RMIT SBITL Analytics Competition Champion", "RMIT", "2016"
) %>%
  brief_entries(competition, year, from)
